# Generated by Django 5.2.9 on 2025-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='User name')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('user_phone', models.CharField(max_length=20, unique=True, verbose_name='User Phone')),
                ('user_password', models.CharField(max_length=256, verbose_name='Password')),
                ('user_created', models.DateTimeField(auto_now_add=True, verbose_name='Data created')),
                ('user_agreed', models.BooleanField(default=False, verbose_name='Agree')),
                ('user_activated', models.BooleanField(default=False, verbose_name='Activated')),
                ('user_banned', models.BooleanField(default=False, verbose_name='Banned')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last visit')),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'Users',
                'ordering': ('-user_created',),
            },
        ),
    ]
